### ISSUE TITLE
Missing Whiteboard journal page type

### ISSUE THREAD

**Issue by franckflo** [patrickporto/journal-whiteboard#1]
## Describe the bug
When I create a new Journal and Journal page, there is no Whiteboard to choose among the page types
![Whiteboard](https://github.com/patrickporto/journal-whiteboard/assets/80221412/510968fa-6bfb-46f7-bc1f-462a220352df)

## To Reproduce
Create New Journal 
Open New Journal 
Add New Page
Click on New Page Type menu

## Expected behavior
Finding Whiteboard in the list, as shown in your screenshot

## Environment (please complete the following information):
 - Foundry VTT: 10.291
 - Browser Opera GX
 - Module Version 11.0.6
 - DnD 2.2.1

## Additional context:
The only two Journal related Modules I have are GMScreen, Thumbnail for Journal Entries and Journal Whiteboard

**Comment by patrickporto** [comment]
I discovered that Foundry V10 has not sub-type support like Foundry V11. I am currently searching for a backport to Foundry V10.

**Comment by franckflo** [comment]
Got it, thanks for letting me know. Maybe Monk’s journal module has a workaround for this ? The module offers multiple subtypes of journals and works with v10.

**Comment by patrickporto** [comment]
I have noticed that the Monk's Journal Module requires several modifications to function properly on Foundry V10. Unfortunately, I have decided not to backport this module to Foundry V10.
