### ISSUE TITLE
Whiteboard not showing up as an option in the create new page menu

### ISSUE THREAD

**Issue by maxobremer** [patrickporto/journal-whiteboard#2]
Like the title says, the whiteboard journal entry page type is not showing up
![image](https://github.com/patrickporto/journal-whiteboard/assets/86924581/247094ee-05cb-46df-8c39-5e6f5f266e1f)
new world with only this module enabled and socketlib as a dependency
Foundry v11 build 302
DnD5e 2.21
Journal whiteboard 11.0.6

**Comment by patrickporto** [comment]
@maxobremer I don't get to reproduce the issue:
![image](https://github.com/patrickporto/journal-whiteboard/assets/1543276/7cb02b0c-6490-4b5f-b0f8-b9d03f9d7912)

**Comment by maxobremer** [comment]
Okay tested it again today, no other modules besides socketlib as per your screenshot, same issue, I uninstall the module, reinstall it and now it works? maybe some leftovers from a previous version that was messing stuff up? idk
