### ISSUE TITLE
Enable .webp files as assets

### ISSUE THREAD

**Issue by acd-jake** [patrickporto/journal-whiteboard#3]
## Is your feature request related to a problem? Please describe.
In FoundryVTT, the .webp file type is recommended for use as assets. Unfortunately, these files cannot currently be used as image assets in the Journal whiteboards. When trying to use a .webp file on a whiteboard, nothing happens and the error message "...not loaded - Extension not allowed." is displayed in the developer console.

## Describe the solution you'd like
Enable the use of .webp files in the Journal whiteboards.

**Comment by patrickporto** [comment]
@acd-jake you are right, whiteboard does not accept webp because [tldraw does not accept webp](https://github.com/tldraw/tldraw/blob/aad5815a06086ae121e11d41f3e297c03c750f48/packages/editor/src/lib/utils/assets.ts#L9). I am going to seek a solution to that issue
