### ISSUE TITLE
No whiteboard in V10 (291)

### ISSUE THREAD

**Issue by Utharlepreux** [patrickporto/journal-whiteboard#4]
The module has been installed and activated 
There is no whiteboard option when creating a new page
System is Warhammer FRPG V4
Info on the forge says it's supposed to work with V10
<img width="1455" alt="Capture d’écran 2023-07-05 à 15 32 45" src="https://github.com/patrickporto/journal-whiteboard/assets/40202908/15c54ca8-3589-4e73-afc3-41c856781088">

**Comment by patrickporto** [comment]
Duplicated https://github.com/patrickporto/journal-whiteboard/issues/1
