### ISSUE TITLE
Error on player side while attempting to close a whiteboard

### ISSUE THREAD

**Issue by mech-tools** [patrickporto/journal-whiteboard#5]
## Describe the bug
Connected with a player account. Open a journal note with full permissions.
Edit the whiteboard, then simply close it.

This throws an error.

## Screenshots
![image](https://github.com/patrickporto/journal-whiteboard/assets/1687854/6284f39d-dfde-40e4-868d-1998e6d23713)

## Environment (please complete the following information):
 - Foundry VTT: 11
 - Browser FF
 - Module Version Latest

**Comment by mech-tools** [comment]
As it turns out, I have the same issue as the GM

**Comment by patrickporto** [comment]
@DarKDinDoN Could you test with the new release?
https://github.com/patrickporto/journal-whiteboard/releases/tag/11.3.1

**Comment by mech-tools** [comment]
Yep, we good. There is another issue with GM Screen now. Will open another ticket.
